#!/usr/bin/env bash

function extension-check() {
    #set -euo pipefail

    if [ $# -eq 0 ]
    then
        echo "Error: Plugin directory missing!" 1>&2
        return 1
    fi

    local PLUGIN_DIR="$1"

    printf "Validating plugin at ${PLUGIN_DIR}\n"

    printf "\nFind \"!important\" in CSS files \n"
    find ${PLUGIN_DIR} -type f \( -name '*.scss' -o -name '*.css' \) ! -path '*/src/Resources/public/administration/*' ! -path '*/node_modules/*' -exec grep -H '\!important' {} \;

    printf "\nCheck for \"FOREIGN_KEY_CHECKS\"\n"
    find ${PLUGIN_DIR} -type f -name '*.php' -exec egrep -Hi 'FOREIGN_KEY_CHECKS' {} \;

    printf "\nCheck for prohibited debugging code (PHP)\n"
    find ${PLUGIN_DIR} -type f -name "*.php" -exec egrep -H '(die|exit|\sdd|dump)' {} \;

    printf "\nCheck for prohibited debugging code (JavaScript)\n"
    find ${PLUGIN_DIR} -type f \( -name "*.js" -o -name "*.ts" -o -name "*.html.twig" \) ! -path '*/src/Resources/public/administration/*'  ! -path '*/node_modules/*' -exec egrep -H '(\sconsole\.)' {} \;

    printf "\nCheck for \"createDefaultContext\"\n"
    find ${PLUGIN_DIR} -type f -name '*.php' -exec egrep -H '\:\:createDefaultContext\(.*\)' {} \;

    printf "\nCheck for manual context creation\n"
    find ${TMPDIR} -type f -name '*.php' -exec egrep -H ' new Context\(' {} \;

    printf "\nFind links (check for suspicious ones)\n"
    find ${PLUGIN_DIR} -type d \( -name 'node_modules' -o -name 'vendor' -o -name 'public' \) -prune -o -type f \( -name 'composer.lock' -o -name 'package-lock.json' -o -name '*.map' \) -prune -o -type f -exec egrep -H 'http[s]*\:\/\/' {} \;

    printf "\nFind path traversals in twig files\n"
    find ${PLUGIN_DIR} -type f -name '*.twig' -exec egrep -H '\.\.\/' {} \;


}

function compare-versions() (
    if [ $# -ne 2 ]
    then
        echo "Error: Missing arguments! Please provide two .zip archives to compare: compare-versions OLD_ZIP NEW_ZIP" 1>&2
        return 1
    fi

    zip_a=$(echo "$(cd "$(dirname "$1")"; pwd)/$(basename "$1")")
    zip_b=$(echo "$(cd "$(dirname "$2")"; pwd)/$(basename "$2")")

    tmpdir=$(mktemp -d 2>/dev/null || mktemp -d -t 'extension-review-diff')

    cd $tmpdir

    git init -q
    unzip -q $zip_a
    git add .
    git commit -m "Initial commit" -q

    rm -rf ./* 

    unzip -q $zip_b 
    git add .

    browse-diff

    rm -rf $tmpdir
)
