#!/bin/bash

function workspace-finder() {
    local ROOT=~/development/
    local DIRS=(
        ~/.config/home-manager
        ~/.config/nvim
    )
    local TMP_DIRS=()

    while IFS=  read -r -d $'\0'; do
        TMP_DIRS+=$(readlink -f $REPLY)
    done < <(find $ROOT -maxdepth 1 -mindepth 1 -type d -print0)

    TMP_DIRS+=("${DIRS[@]}")

    local TARGET_DIR=$(printf '%s\n' "${TMP_DIRS[@]}" | fzf)

    [ $TARGET_DIR ] || return 0

    cd "${TARGET_DIR}"
}
