source $HOME/.aliases
source $HOME/.devenvrc
source $HOME/.prompt

for function in $HOME/.functions/??*; do
    source $(realpath $function)
done

# Workaround for broken NIX_PATH 
export NIX_PATH=home-manager=/home/baek/.nix-defexpr/channels/home-manager:nixpkgs=/home/baek/.nix-defexpr/channels/nixpkgs
