#!/bin/bash

function workspace-finder() {
    local ROOT=~/development/
    local DIRS=(
        ~/terminal 
        ~/.config/nvim
    )
    local TMP_DIRS=()

    local OPTSTRING=":t"
    local OPTIND

    local tmuxSession=0

    while getopts ${OPTSTRING} opt; do
        case ${opt} in
            t)
                tmuxSession=1
                ;;
        esac
    done

    readarray -d '' TMP_DIRS < <(find $ROOT -maxdepth 1 -mindepth 1 -type d -print0)

    TMP_DIRS+=("${DIRS[@]}")

    local TARGET_DIR=$(printf '%s\n' "${TMP_DIRS[@]}" | fzf)

    [ $TARGET_DIR ] || exit 0

    if [ "$TMUX" ]; then
        tmux new-window -t $(tmux display-message -p '#S'): -c $TARGET_DIR
    elif [ $tmuxSession -eq 1 ]; then
        tmux new-session -c $TARGET_DIR
    else
        cd "${TARGET_DIR}"
    fi
}
