#!/bin/bash

alias cc="clear"
alias ll='ls -laht'
alias tree="find . -print | sed -e 's;[^/]*/;|____;g;s;____|; |;g'"

alias yolo="git push -f"
alias sw="git switch"
alias p="git push"
alias s="git status"
alias d="git diff"
alias l="git log --graph --abbrev-commit --decorate --format=format:'%C(bold blue)%h%C(reset) - %C(bold green)(%ar)%C(reset) %C(white)%s%C(reset) %C(dim white)- %an%C(reset)%C(auto)%d%C(reset)' --all"
alias l2="git log --graph --abbrev-commit --decorate --format=format:'%C(bold blue)%h%C(reset) - %C(bold cyan)%aD%C(reset) %C(bold green)(%ar)%C(reset)%C(auto)%d%C(reset)%n''          %C(white)%s%C(reset) %C(dim white)- %an%C(reset)'"
alias fp="git fetch && git pull"
alias c="git commit"
alias ca="git commit --amend"
alias ga="git add ."
alias gcl="git clean -fd"
alias grs="git reset --soft"
alias grh="git reset --hard"

alias wf="workspace-finder"

alias zed="open -a /Applications/Zed.app -n"
