source $HOME/.aliases
source $HOME/.devenvrc
source $HOME/.prompt

for function in $HOME/.functions/??*; do
    source $(realpath $function)
done

# macOS specific
export BASH_SILENCE_DEPRECATION_WARNING=1

# Workaround for weird ubuntu multi-user installation
export NIX_PATH=home-manager=/home/baek/.nix-defexpr/channels/home-manager:unstable=/home/baek/.nix-defexpr/channels/unstable
